import pandas as pd

#print options
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', 1000)

#first table (series)
s=pd.Series(['black','Snape','is','a','shitshow'])
s.index=(['first argument', 'second argument', 'third argument', 'fourth argument', 'fifth argument'])
print(s)
print (s['fifth argument'])

#second table (dataframe)
fans_opinions=pd.DataFrame(
    {
    "Black Snape supporters":
    [
     "Character Universality.",
     "Focus on Nuance.",
     "Challenging Tropes.",
     "Representation Beyond Visuals. "
    ],

     "Black Snape opponents":
     [
     "Canon Inaccuracy.",
     "Racialized Bullying Optics.",
     "'Tokenism' Concerns.",
     "Distraction from Character."
     ]
     },
     index=['Opinion 1','Opinion 2','Opinion 3','Opinion 4']
     )
print (fans_opinions)
print ("fans_opinions.shape: ",fans_opinions.shape)

#importing the data from anaconda3 example .csv file
panda_review1=pd.read_csv('D:/development-resources/Anaconda3/Lib/site-packages/matplotlib/mpl-data/sample_data/Stocks.csv')
print ("uploaded file 'panda_review1': \n", panda_review1.head(5)) #only 4 rows

#importing data from my .csv file, the file is generated by DeepSeek (it chose the space topic)
panda_review2=pd.read_csv("./python-simple-programs/010. pandas_data.csv", index_col=0) #use the column0 as index
print ("uploaded file 'panda_review2': \n", panda_review2)

#head (only 5 rows)
print (panda_review2.head())